# Generated by Django 6.0.5 on 2026-07-01 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cover_image',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
