# Generated by Django 5.2.15 on 2026-06-30 13:22

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('money', 'Money'), ('points', 'Points')], max_length=16)),
                ('currency', models.CharField(blank=True, default='', max_length=12)),
                ('status', models.CharField(choices=[('active', 'Active'), ('frozen', 'Frozen'), ('closed', 'Closed')], default='active', max_length=16)),
                ('available_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('held_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wallet_wallet',
                'ordering': ('kind', 'currency'),
            },
        ),
        migrations.CreateModel(
            name='WalletLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry_type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit'), ('hold', 'Hold'), ('release', 'Release'), ('capture', 'Capture'), ('adjustment', 'Adjustment')], max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=18)),
                ('held_balance_after', models.DecimalField(decimal_places=2, max_digits=18)),
                ('reason', models.CharField(choices=[('admin_adjustment', 'Admin adjustment'), ('goal_stake_hold', 'Goal stake hold'), ('goal_stake_release', 'Goal stake release'), ('goal_stake_capture', 'Goal stake capture'), ('reward', 'Reward'), ('refund', 'Refund')], max_length=40)),
                ('reference_type', models.CharField(blank=True, max_length=80)),
                ('reference_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=160, null=True, unique=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_ledger_entries', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='wallet.wallet')),
            ],
            options={
                'db_table': 'wallet_ledger_entry',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['user', 'kind'], name='wallet_user_kind_idx'),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.UniqueConstraint(fields=('user', 'kind', 'currency'), name='uniq_user_wallet_kind_currency'),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.CheckConstraint(condition=models.Q(('available_balance__gte', 0)), name='wallet_available_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.CheckConstraint(condition=models.Q(('held_balance__gte', 0)), name='wallet_held_non_negative'),
        ),
        migrations.AddIndex(
            model_name='walletledgerentry',
            index=models.Index(fields=['wallet', '-created_at'], name='ledger_wallet_created_idx'),
        ),
        migrations.AddIndex(
            model_name='walletledgerentry',
            index=models.Index(fields=['user', '-created_at'], name='ledger_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='walletledgerentry',
            index=models.Index(fields=['reference_type', 'reference_id'], name='ledger_reference_idx'),
        ),
        migrations.AddConstraint(
            model_name='walletledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='wallet_ledger_amount_positive'),
        ),
    ]
