# Generated by Django 5.2.15 on 2026-06-30 13:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('goal_type', models.CharField(choices=[('solo', 'Solo'), ('group', 'Group')], default='solo', max_length=16)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('failed', 'Failed'), ('paused', 'Paused'), ('archived', 'Archived')], default='active', max_length=16)),
                ('progress', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('stake_points', models.PositiveIntegerField(default=0)),
                ('schedule_label', models.CharField(blank=True, max_length=160)),
                ('cover_color', models.CharField(blank=True, max_length=40)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'goals_goal',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='GoalMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member')], default='member', max_length=16)),
            ],
            options={
                'db_table': 'goals_goal_member',
                'ordering': ('created_at',),
            },
        ),
    ]
