# Generated by Django 5.2.15 on 2026-06-29 09:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=80)),
                ('goal_type', models.CharField(choices=[('solo', 'Solo'), ('group', 'Group')], default='solo', max_length=16)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('failed', 'Failed'), ('paused', 'Paused'), ('archived', 'Archived')], default='active', max_length=16)),
                ('progress', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('stake_points', models.PositiveIntegerField(default=0)),
                ('schedule_label', models.CharField(blank=True, max_length=160)),
                ('cover_color', models.CharField(blank=True, max_length=40)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'goals_goal',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='GoalMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member')], default='member', max_length=16)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='goals.goal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'goals_goal_member',
                'ordering': ('created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['owner', 'status'], name='goals_owner_status_idx'),
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['category'], name='goals_category_idx'),
        ),
        migrations.AddIndex(
            model_name='goalmember',
            index=models.Index(fields=['user', 'role'], name='goal_member_user_role_idx'),
        ),
        migrations.AddConstraint(
            model_name='goalmember',
            constraint=models.UniqueConstraint(fields=('goal', 'user'), name='uniq_goal_member'),
        ),
        migrations.AddConstraint(
            model_name='goalmember',
            constraint=models.CheckConstraint(condition=models.Q(('role__in', ('owner', 'admin', 'member'))), name='valid_goal_member_role'),
        ),
    ]
