# Generated by Django 5.2.15 on 2026-06-30 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goals', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_goals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='goalmember',
            name='goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='goals.goal'),
        ),
        migrations.AddField(
            model_name='goalmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['owner', 'status'], name='goals_owner_status_idx'),
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['category'], name='goals_category_idx'),
        ),
        migrations.AddIndex(
            model_name='goalmember',
            index=models.Index(fields=['user', 'role'], name='goal_member_user_role_idx'),
        ),
        migrations.AddConstraint(
            model_name='goalmember',
            constraint=models.UniqueConstraint(fields=('goal', 'user'), name='uniq_goal_member'),
        ),
        migrations.AddConstraint(
            model_name='goalmember',
            constraint=models.CheckConstraint(condition=models.Q(('role__in', ('owner', 'admin', 'member'))), name='valid_goal_member_role'),
        ),
    ]
