# Generated by Django 6.0.5 on 2026-07-12 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goalmember',
            name='outcome',
            field=models.CharField(choices=[('committed', 'Committed'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='committed', max_length=16),
        ),
        migrations.AddField(
            model_name='goalmember',
            name='stake_amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
