# Generated by Django 6.0.5 on 2026-07-12 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0004_goalmember_outcome_goalmember_stake_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('media', models.FileField(upload_to='proofs/%Y/%m/')),
                ('note', models.TextField(blank=True, max_length=1000)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_proofs', to=settings.AUTH_USER_MODEL)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proofs', to='goals.goal')),
            ],
            options={
                'db_table': 'goals_goal_proof',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ProofReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vote', models.CharField(choices=[('approve', 'Approve'), ('reject', 'Reject')], max_length=16)),
                ('proof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='goals.goalproof')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proof_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'goals_proof_review',
                'ordering': ('created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='goalproof',
            index=models.Index(fields=['goal', '-created_at'], name='proof_goal_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='goalproof',
            constraint=models.UniqueConstraint(fields=('goal', 'author'), name='uniq_goal_proof_author'),
        ),
        migrations.AddConstraint(
            model_name='proofreview',
            constraint=models.UniqueConstraint(fields=('proof', 'reviewer'), name='uniq_proof_reviewer'),
        ),
    ]
