# Generated by Django 6.0.5 on 2026-07-12 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0005_goalproof_proofreview_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goalmember',
            name='status',
            field=models.CharField(choices=[('invited', 'Invited'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='invited', max_length=16),
        ),
    ]
