# Generated by Django 6.0.5 on 2026-07-12 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0006_goalmember_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='cover_image',
            field=models.FileField(blank=True, upload_to='goals/%Y/%m/'),
        ),
    ]
