# Generated by Django 6.0.5 on 2026-07-12 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='media',
            field=models.FileField(blank=True, upload_to='posts/%Y/%m/'),
        ),
    ]
